kind: Service
apiVersion: v1
metadata:
  name: mycat-svc
  namespace: db
spec:
  type: NodePort
  selector:
    app: mycat
  ports:
  - name: data
    protocol: TCP
    port: 8066
  - name: admin
    protocol: TCP
    port: 9066