# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysqlset1
  labels:
    app: mysql-set1
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql-set1
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysqlset1-read
  labels:
    app: mysql-set1
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql-set1